name: CI on Linux

on:
  push:
  pull_request:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.15.4
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "Coverage gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            build: coverage
            build_type: Coverage
            cxx_flags: "-std=c++23"

          - name: "gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc10"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release
            cxx_flags: "-std=c++20"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: raptor
          fetch-depth: 2
          submodules: true

      - name: Add package source
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install ccache
        run: |
          conda install --yes --override-channels --channel conda-forge ccache
          sudo ln -s $CONDA/bin/ccache /usr/bin/ccache

      - name: Install compiler ${{ matrix.cxx }}
        run: sudo apt-get install --yes ${{ matrix.cxx }}

      - name: Install gcovr
        if: matrix.build == 'coverage'
        env:
          CC: ${{ matrix.cc }}
        run: |
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/${CC/gcc/gcov} 100
          pip install gcovr==5.0

      - name: Load ccache
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../raptor -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                          -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                          -DRAPTOR_NATIVE_BUILD=OFF

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: ${{ matrix.build == 'coverage' && '125M' || '50M' }}
          CCACHE_IGNOREOPTIONS: "-fprofile-abs-path"
        run: |
          ccache -z
          cd build
          make VERBOSE=1 -k -j2 api_test cli_test
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j2 --output-on-failure

      - name: Generate coverage report
        if: matrix.build == 'coverage'
        run: |
          gcovr --gcov-executable ${{ github.workspace }}/raptor/lib/seqan3/.github/workflows/scripts/gcov.sh \
                --root ${{ github.workspace }}/raptor/test/coverage \
                ${{ github.workspace }}/build \
                --filter ${{ github.workspace }}/raptor/include \
                --filter ${{ github.workspace }}/raptor/src \
                --exclude-lines-by-pattern '^\s*$' \
                --exclude-lines-by-pattern '^\s*};$' \
                --exclude-lines-by-pattern '^.*GCOVR_EXCL_LINE.*$' \
                --exclude-unreachable-branches \
                --exclude-throw-branches \
                -j 2 \
                --xml \
                --output ${{ github.workspace }}/build/coverage_report.xml

      - name: Submit coverage report
        if: matrix.build == 'coverage'
        uses: codecov/codecov-action@v2
        with:
          files: ${{ github.workspace }}/build/coverage_report.xml
          root_dir: ${{ github.workspace }}/raptor
